### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by crisboarna**
Hi @Makeshift ,

1. I added linting to the project in order to fix issues that arise during coding. 
- Why?
Read [here](https://hackernoon.com/how-linting-and-eslint-improve-code-quality-fa83d2469efe).
- What is the outcome ?
~900 potential bugs from trivial to severe found and fixed.
- What rules have I used ?
The coding rules applied are used internally by Airbnb, standardized, published and widely used by the community as an Javascript Style Guide. Explanation of each rule is found [here](https://github.com/airbnb/javascript). (It is an educational read)
- How do I use it ?
Run `npm run lint`. It will fix most issues by itself making the code much cleaner. For more ambiguous sections it will just highlight the issue that can then be fixed. If used in conjunction with point 2 below it will ensure standardized code with fewer issues reaches repo. 
- Notes
Some rules have been modified or disabled due to requiring more thorough changes which need their own pull request. Most notably 'no-undef' rule which reveals snippets of code that will throw an error 100% of the time. 
  - You can find examples of these error areas by searching for `// eslint-disable-next-line no-undef`
  - All rules can be tweaked or disabled entirely by adding appropriate line in `package.json` `eslintConfig` section by referencing the defined [rules](https://eslint.org/docs/rules/).

  Folder structure is changed as well for clarity, future tests and for linting to function.

2. Added Git conventional commit message styles
 - Why ?
Read [here](https://github.com/commitizen/cz-cli#commitizen-for-project-maintainers). 
It pretty much allows easier perusal of commit history by all contributors to zero in on searched for commit or to programatically generate Release, to sort, etc.
- What style is it in ?
It is using the AngularJS commit message format. You can already see it in action on my commits.
- How do I use it ?
Instead of committing via git commit, use the wrapper `npm run commit` which has the added advantage of running any other script beforehand to check code such as linting, testing, building, etc.
- Note
This is optional feature that does not obstruct the development process, it only enhances it and is optional, `git commit` can still be used without interference.

3. Changed Dockerfile project uid & guid
- Why ?
Due to mounting local src files into container and container executing project with root user would create logs directory with root user making it inaccessible by host user. Now container is running process with same uid& guid as host user bridging it seamlessly.

I know this looks like a big commit. 99.9% of the changes are from running the linting and resulting bug fixing. the 0.1% are changes to `Dockerfile`, `docker-compose.yaml` and `package.json`.

This should help towards the process of bringing project out of heavy alpha ;)
I think I will next look at adding async/await and helping with all the nested functions/callbacks :D

Hope you like the changes :)

### CODE REVIEW

**Comment by Makeshift** [comment]
I uh, will try and deal with conflicts soon :P

**Comment by crisboarna** [comment]
Hi @Makeshift ,

I have merged the latest changes into the branch :)

Good to go ?

**Comment by Makeshift** [comment]
So a couple of questions I have about this, as linting is pretty new to me:

- What's with the choice of putting source files into /src? Since we aren't compiling anything that confuses me a little
- The majority of the changes to the source seem to be changing 'var' to 'let' and 'const' depending on usage. 'let' I believe is primarily for scoping reasons and 'const' is obviously for variables that don't change. Are all these changes found and done by the linter?
- There are also a lot of redefining various functions in odd ways I haven't seen before, I assume these are just more modern ways of doing things - My JS knowledge is a couple years out of date. However this could be problematic for maintaining the code as we're now doing things in a way I'm not used to.
- Seriously in some cases this looks horrible. What the crap kind of layout is [this](https://github.com/Makeshift/eve-goons-waitlist/pull/92/files#diff-45117cbb9236bdbc1cd9120fcc626b3bR9)?

Obviously with such a huge changeset it's very hard for me to properly review these changes, you could have slipped basically anything in, so sorry for me taking time.

**Comment by crisboarna** [comment]
Hi,
1. Files are put into src due to:
- Makes clear differentiation between JS code and other assets, it does not have to be compiled to be clearly segregated for clarity
- Linter requires to have path specified, ensures only JS code is linted and not node_modules
- Although currently there are no tests, it is  good to have a clear differentiation between `src` and `tests` folders so you can at a glance understand what is where from root of project. 
- Further sub-folders can be seen to naturally emerge with some already implemented such as `controllers` , `views`, `storage`, `services`, `utils` although that is perhaps for another day :)
2. The majority of the var changes are done by linter, in some cases it is ambiguous and it requires input from developer. Changing them is important due to hoisting ( more details [here](https://github.com/airbnb/javascript#hoisting)) which results in vars being part of global scope which can insert tricky, hair pulling bugs.
3. The function redefinitions that I recall are related to this [recommendation](https://github.com/airbnb/javascript#functions). Others that I recall were changing of some `function() {}` to `()=>{}` for empty parameter passing, other cases I do not recall.
The changes I have done are aimed towards reducing the complexity of the code base. It is aimed towards allowing the code to be read sequentially and to understand the meaning behind every line as is. I tried in not introducing very different concepts from those already there. If you have any questions regarding the method we can talk it over Jabber for clarification.
4. That layout is created by the linter as it ensures all variables are visible and easily readable. This rule is defined [here](https://eslint.org/docs/rules/indent#functiondeclaration) One of the reason it does it is to reduce line length. Line length up to a certain limit is commonly enforced to be up to 80 characters. I have customized the rule so it allows up to 120 characters. This can be found in `package.json` -> `eslintConfig` -> `max-len`. It is found to provide much more information more concisely having it ordered vertically in blocks rather than having to read horizontally.

**Comment by Makeshift** [comment]
Thank you for the explanations - I'll take a read through the resources you linked and see if I can finish off reading over the code this evening before merging it.

**Comment by Makeshift** [comment]
This seems to have fucked up logging, fleet at a glance, and just straight up crashes when you try and open the FC management page. I don't have time to debug it right now so for the moment I'm not merging this.

**Comment by crisboarna** [comment]
Added fixes for the aforementioned issues. Was related to function out of scope due to the internal module usage. Fleet management, fleet at a glance and logging seem to be working good now based on the issues you described.

Have a try ? :)

**Comment by crisboarna** [comment]
Updated with latest merges.

**Pull request closed without merging**
